export const experiences = [
  {
    company: "ConnectingDots Infotech",
    role: "Software Developer",
    duration: "June 2023 - April 2026",
    location: "Pune(Remote)",
    technologies: [
      { icon: "angular.svg", name: "Angular" },
      { icon: "react.svg", name: "React" },
      { icon: "nextjs.svg", name: "Next.js" },
      { icon: "tailwind.svg", name: "Tailwind CSS" },
      { icon: "bootstrap.svg", name: "Bootstrap" },
      { icon: "scss.svg", name: "SCSS" },
      { icon: "typescript.svg", name: "TypeScript" },
      { icon: "nodejs.svg", name: "Node.js" },
      { icon: "postman.svg", name: "Postman" },
    ],
    description: [
      "Built modular Angular applications for OTT and SaaS platforms using reusable, feature-based architecture.",
      "Centralized data flow with RxJS, reducing redundant API calls and improving performance.",
      "Developed live streaming and private call features with real-time UI interactions.",
      "Improved load performance through lazy loading and optimized component rendering.",
      "Integrated Razorpay, Stripe, and Paytm with complete payment flows including checkout and verification.",
      "Streamlined support workflows by consolidating multiple tools into a single Freshdesk plugin.",
      "Collaborated with cross-functional teams to deliver scalable features and enhance user experience.",
    ],
    projects: [
      {
        title: "Chottulink",
        projectDescription: "SaaS for deeplinking",
        url: "https://chottulink.com",
        icon: "chottulink.png",
        description: [
          "Built and maintained marketing website, user dashboard, and admin panel within a unified Angular codebase supporting multi-role access",
          "Designed reusable UI components to standardize workflows and improve maintainability",
          "Implemented RxJS-based observable caching to prevent duplicate API calls and sync data across modules",
          "Developed reusable analytics components using ApexCharts for link performance visualization",
          "Optimized performance using lazy loading and efficient state management strategies",
          "Built a reusable QR code generator using ZXing with branding support (logo overlays and themes)",
          "Integrated Google OAuth login with secure token and session management",
        ],
      },
      {
        title: "ULLU",
        projectDescription: "OTT platform",
        url: "https://ullu.app",
        icon: "ullu.png",
        description: [
          "Maintained and scaled a high-traffic OTT platform with ~3.26M monthly visits",
          "Implemented live streaming and private call features using Agora SDK",
          "Integrated multiple payment gateways including Razorpay, Stripe, and Paytm with full checkout flows",
        ],
      },
      {
        title: "HariOm OTT Platform",
        projectDescription: "Spiritual and Devotional App",
        url: "https://hariom.app",
        icon: "hariom.webp",
        description: [
          "Improved content discoverability through better trailer visibility and episode layout restructuring",
          "Integrated Google IMA Ads with Video.js for ad delivery",
          "Enhanced a custom Video.js player with playlist, audio/video modes, and synchronized lyrics",
          "Built an online temple booking system for scheduling visits",
          "Developed a Flutter-based Android TV application",
          "Implemented D-pad navigation and custom focus management optimized for TV interfaces",
        ],
      },
      {
        title: "Atrangii",
        projectDescription: "OTT platform",
        url: "https://atrangii.in",
        icon: "atrangii.webp",
        description: [
          "Integrated multiple payment gateways including Razorpay, Stripe, Paytm, PayPal, HDFC PayZapp, and SabPaisa",
          "Improved website performance by 35% using optimized Angular rendering strategies",
          "Integrated Google IMA Ads for monetization",
          "Enabled PWA support with service workers and offline caching",
          "Enhanced custom media player with gesture seek, playback speed control, and subtitle support",
        ],
      },
    ],
  },
  {
    company: "Genex Corporate Services Ltd",
    role: "Intern Software Developer",
    duration: "Jan 2023 - May 2026",
    location: "Hyderabad(Remote)",
    technologies: [
      { icon: "tailwind.svg", name: "Tailwind CSS" },
      { icon: "react.svg", name: "React" },
      { icon: "nodejs.svg", name: "Node.js" },
      { icon: "postman.svg", name: "Postman" },
      { icon: "express.svg", name: "Express.js" },
      { icon: "javascript.svg", name: "JavaScript" },
      { icon: "material-ui.svg", name: "Material UI" },
    ],
    description: [
      "Revamped the Vorkinsta website with improved UI and UX.",
      "Developed responsive React components for a rent management system.",
      "Integrated REST APIs in collaboration with backend teams.",
    ],
    projects: [
      {
        title: "Vorkinsta",
        projectDescription: "IT Consulting Website",
        url: "https://www.vorkinsta.com/",
        icon: "vorkinsta.jpg",
        description: [
          "Revamped the entire website using HTML, CSS, and JavaScript with a focus on modern UI and responsiveness",
          "Improved overall user experience through cleaner layouts and optimized front-end structure",
          "Ensured cross-browser compatibility and consistent performance across devices",
        ],
      },
      {
        title: "Genex Corporate Services Ltd",
        projectDescription: "Corporate Website",
        url: "https://www.genexcorp.com/",
        icon: "genex.jpg",
        description: [
          "Developed a new corporate website from scratch with a clean and professional UI",
          "Implemented responsive design to ensure seamless experience across devices",
          "Structured the frontend for scalability and easy content updates",
        ],
      },
      {
        title: "Rent App",
        projectDescription: "Rent Management Application",
        url: null,
        icon: null,
        description: [
          "Built the frontend for a rent management application for property owners using React and Material UI",
          "Designed interfaces to track tenant records, payments, and rental details",
          "Implemented form handling and structured UI flows for efficient data management",
        ],
      },
    ],
  },
];
